#!/bin/sh
#
# backup Blackhole, Abyss, Caldera, and Logs
# run from /etc/cron.daily
#
# must be run as root
#

echo '********************************************************' >> /media/Caldera/Logs/bkup.log
echo '**** BlackHole backup started  - ' $(date) >> /media/Caldera/Logs/bkup.log
mount -lv UUID=6bb923c4-6ee3-4623-bdf9-a3a9d06a6b9b  /mnt/BlackHoleBkp >> /media/Caldera/Logs/bkup.log
rsync   -avH  --delete   /media/BlackHole/ /mnt/BlackHoleBkp/ >> /media/Caldera/Logs/bkup.log
sleep 2
umount -lv /mnt/BlackHoleBkp  >> /media/Caldera/Logs/bkup.log 2>&1
echo '**** BlackHole backup finished - ' $(date) >> /media/Caldera/Logs/bkup.log

echo  '**** Abyss backup started  - ' $(date)>> /media/Caldera/Logs/bkup.log
mount -lv UUID=affc284d-5f53-4353-81d3-eb22f45856ad  /mnt/AbyssBkp >> /media/Caldera/Logs/bkup.log
rsync   -avH  --delete   /media/Abyss/ /mnt/AbyssBkp/ >> /media/Caldera/Logs/bkup.log
sleep 2
umount -lv /mnt/AbyssBkp  >> /media/Caldera/Logs/bkup.log 2>&1
echo '**** Abyss backup finished - ' $(date) >> /media/Caldera/Logs/bkup.log

echo  '**** Caldera backup started  - ' $(date)>> /media/Caldera/Logs/bkup.log
mount -lv UUID=48d3ba3f-65eb-4ef1-a143-246e89f1988c  /mnt/CalderaBkp >> /media/Caldera/Logs/bkup.log 2>&1
rsync   -avH  --delete   /media/Caldera/ /mnt/CalderaBkp/ >> /media/Caldera/Logs/bkup.log
sleep 2
umount -lv /mnt/CalderaBkp  >> /media/Caldera/Logs/bkup.log 2>&1
echo '**** Caldera backup finished - ' $(date) >> /media/Caldera/Logs/bkup.log 2>&1

echo '**** Video backup started  - ' $(date) >> /media/Caldera/Logs/bkup.log
mount -lv UUID=5c987372-bb54-440e-8a37-7dd51c988524  /mnt/VideoBkp >> /media/Caldera/Logs/bkup.log
rsync   -avH  --delete   /media/Video/ /mnt/VideoBkp/ >> /media/Caldera/Logs/bkup.log
sleep 2
umount -v /mnt/VideoBkp
echo '**** Video backup finished - ' $(date) >> /media/Caldera/Logs/bkup.log 2>&1

echo  '**** all backups complete - ' $(date) '\nnormal termination\n' >> /media/Caldera/Logs/bkup.log
echo  '**** all backups complete - ' $(date) '\nnormal termination\n'