#!/bin/bash
#
# backup Blackhole, Abyss, Images, and Logs
#

echo '********************************************************' >> /media/Logs/bkup-log.log
echo '**** BlackHole backup started  - ' $(date) >> /media/Logs/bkup-log.log
mount -lv UUID=6bb923c4-6ee3-4623-bdf9-a3a9d06a6b9b  /media/BlackHole_bkup >> /media/Logs/bkup-log.log
rsync   -avH  --delete  /media/BlackHole/ /media/BlackHole_bkup/ >> /media/Logs/bkup-log.log
sleep 2
umount -lv /media/BlackHole_bkup  >> /media/Logs/bkup-log.log 2>&1
echo '**** BlackHole backup finished - ' $(date) >> /media/Logs/bkup-log.log

echo  '**** Abyss backup started  - ' $(date)>> /media/Logs/bkup-log.log
mount -lv UUID=affc284d-5f53-4353-81d3-eb22f45856ad  /media/Abyss_bkup >> /media/Logs/bkup-log.log
rsync   -avH  --delete  /media/Abyss/ /media/Abyss_bkup/ >> /media/Logs/bkup-log.log
sleep 2
umount -v /media/Abyss_bkup  >> /media/Logs/bkup-log.log 2>&1
echo '**** Abyss backup finished - ' $(date) >> /media/Logs/bkup-log.log

echo  '**** Images backup started  - ' $(date)>> /media/Logs/bkup-log.log
mount -lv UUID=affc284d-5f53-4353-81d3-eb22f45856ad  /media/Images_bkup >> /media/Logs/bkup-log.log
rsync   -avH  --delete  /media/Images/ /media/Images_bkup/ >> /media/Logs/bkup-log.log
sleep 2
umount -v /media/Images_bkup  >> /media/Logs/bkup-log.log 2>&1
echo '**** Images backup finished - ' $(date) >> /media/Logs/bkup-log.log

# echo '**** Logs backup started  - ' $(date) >> /media/Logs/bkup-log.log
# mount -lv UUID=69e4e0f1-9d85-4036-b62f-823b6fef4b8e  /media/Logs_bkup >> /media/Logs/bkup-log.log
# # # rsync   -avH  --delete  /media/mam1/Logs/ /media/mam1/Logs_bkup/ >> /media/Logs/bkup-log.log
# sleep 2
# umount -v /media/Logs_bkup
# echo '**** Logs backup finished - ' $(date) >> /media/Logs/bkup-log.log 2>&1
echo  -e '**** all backups complete - normal termination\n' >> /media/Logs/bkup-log.log
echo  -e '**** all backups complete - normal termination\n'